### ISSUE TITLE
ACL options

### ISSUE THREAD

**Issue by stefangweichinger** [debops/ansible-samba#16]
how to get options deployed like in 

https://wiki.samba.org/index.php/Setting_up_a_Share_Using_Windows_ACLs#Enable_Extended_ACL_Support_in_the_smb.conf_File

?
Do they have to be added to the role or may they get added within some specific (and existing) variable?

**Comment by drybjed** [comment]
At the moment you could specify them in the `samba__global_custom` hash. This role needs to be rewrtitten to make things like these easier to do though. I guess it will be done at some point, but not just now - other things to do at the moment.

**Comment by stefangweichinger** [comment]
Do I have to use a specific formatting for the options inside that hash? thanks.

**Comment by drybjed** [comment]
You could try putting the option names with spaces in `''` quotation marks.

**Comment by stefangweichinger** [comment]
I see. Will test on a non-productive machine first ;-) (always a good idea).
Maybe I provide my example for the docs then?

**Comment by drybjed** [comment]
Sure, however if you want to do a PR, do it against the new [`debops/debops`](https://github.com/debops/debops/) repository. Keep in mind that the Samba role is in a subdirectory.

More info here: https://lists.debops.org/pipermail/debops-users/2017-October/000102.html

**Comment by stefangweichinger** [comment]
Let me be lazy for now and paste my example in here. PR later, ok?

```
# host_vars file for specific machine

samba__global_custom:
  vfs_objects: 'acl_xattr'
  map_acl_inherit: 'yes'
  store_dos_attributes: 'yes'

# sgw: above vfs_objects setting needs additional vfs-modules pkg installed
samba__base_packages:
  - 'samba'
  - 'samba-common'
  - 'samba-common-bin'
  - 'samba-vfs-modules'
``` 
tested right now, generates working config on target machine.
