### ISSUE TITLE
Handler restart fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by jaapio** [debops/ansible-samba#2]
failed: [server] => {"failed": true}
msg: Failed to start samba.service: Unit samba.service is masked.

when running service samba restart on the command line I get the same message.

**Comment by drybjed** [comment]
Thanks for the bug report. I haven't yet tried Samba on `systemd` OS, but it looks like it's somehow disabled? Check in `/etc/systemd/system/` if there's a symlinked `samba.service` to `/dev/null`.

**Comment by jaapio** [comment]
there is no samba.service in /etc/systemd in any of the underlying folders.

**Comment by PonderingGrower** [comment]
As far as I can tell in systems using `systemd` you are supposed to restart two services: `smbd` and `nmbd`.

So far I just get by by setting `samba_service_name` to just `smbd` but it would be nice to be able to provide like an array: `[ 'smbd', 'nmbd' ]`

**Comment by drybjed** [comment]
I would go with separate handlers for each one. At the moment I don't have access to samba server set up on a `systemd` host, I'll check it out when I get the chance.

**Comment by argent-smith** [comment]
I have just stumbled upon the same thing on 15.10 which is also a systemd thing. The authors of Samba say that masking symlink is intentional and Samba starts via the oldschool init.

**Comment by carxwol** [comment]
I had the same problem on a Debian stretch and i just put samba__service_name: "smbd", but the handler just reload the service, not restart it. It's necessary when you change the samba__workgroup or samba__netbios_name variables.

**Comment by nexudx** [comment]
Same here on ubuntu 16.04 - I' don't know how to solve that by myself
"Unable to start service samba: Failed to start samba.service: Unit samba.service is masked."

**Comment by drybjed** [comment]
This is due to Debian moving from init scripts to systemd unit files. The `nmbd` and `smbd` services are now separate, and the `samba` service is therefore masked.

I [updated the `debops.samba` role in the monorepo](https://github.com/debops/debops/commit/6ea02376d38a992671dcde44171e34f75b9610ba), if you want to copy over the fixed handlers to your role (not sure yet when the roles are exported, sorry). I suppose that the role should still restart the daemons instead of only reloading them, but I didn't want to change the role too much yet - this change was made to fix an issue with testing the role on Debian Stretch. More invasive changes will be done once the new test framework is finished.

**Comment by nexudx** [comment]
Thanks for that hint. I updated the handler almost as described.
On ubuntu 16.04 the nmbd service could not be reloadet.

`Usage: /etc/init.d/nmbd {start|stop|restart|force-reload|status}`

so this solution works for me:
```
- name: Check samba config
  command: testparm -s
  notify: [ 'Restart nmbd', 'Reload smbd' ]

- name: Restart nmbd
  service:
    name: 'nmbd'
    enabled: 'yes'
    state: 'restarted'
  when: ('samba' in samba__base_packages)

- name: Reload smbd
  service:
    name: 'smbd'
    enabled: 'yes'
    state: 'reloaded'
  when: ('samba' in samba__base_packages)
```
